---

- hosts: nous

  remote_user: root
  tasks:

  - name: assegurem regles de firewall
    firewalld:
      rich_rule: 'rule family=ipv4 source address=192.168.0.0/16 accept'
      permanent: true
      state: enabled
  - name: reiniciem el firewall
    command: firewall-cmd --reload

  - name: asegurar wget
    yum: name=wget state=present 

  - name: asegurar paquets de devel
    yum: name="@Development tools" state=present

  - name: instalar openmpi
    yum: name="openmpi" state=present

  - name: repositori de glusterfs
    yum: name="centos-release-gluster" state=present

  - name: client de NIS instalat
    yum: name=ypbind state=present
  
  - name: configuracio del /etc/hosts
    copy: src=/root/templates/hosts.nodes dest=/etc/hosts

  - name: configuracio del client
    copy: src=/root/templates/nisclient.conf dest=/etc/yp.conf

  - name: configurem el nsswitch.conf
    copy: src=/root/templates/nsswitch.conf dest=/etc/nsswitch.conf

  - name: client de NIS engegat
    service: name=ypbind state=started

  - name: client glusterfs instalat
    yum: name=glusterfs state=present

  - name: client glusterfs-fuse instalat
    yum: name=glusterfs-fuse state=present

  - name: paquet attr instalat
    yum: name=attr state=present

  - name: creem el punt de muntatge /soft
    file: path=/soft state=directory

  - name: creem punt de muntatge /users/sbi
    file: path=/users/sbi state=directory

  - name: creem el punt de muntatge /users/genomics
    file: path=/users/genomics state=directory

  - name: creem punt de muntatge /users/syspharm
    file: path=/users/syspharm state=directory

  - name: muntem /soft
    mount:
      path: /soft
      src:  gluster1.hydra:/Soft
      fstype: glusterfs
      opts: _netdev
      state: mounted

  - name: muntem /users/sbi
    mount:
      path: /users/sbi
      src: gluster1.hydra:/Sbi
      fstype: glusterfs
      opts: _netdev
      state: mounted

  - name: muntem /users/genomics
    mount:
      path: /users/genomics
      src: gluster1.hydra:/Genomics
      fstype: glusterfs
      opts: _netdev
      state: mounted

  - name: muntem /users/syspharm
    mount:
      path: /users/syspharm
      src: gluster1.hydra:/Syspharm
      fstype: glusterfs
      opts: _netdev
      state: mounted


  - name: copiem lmod.sh al /etc/profile.d
    copy: src=/root/templates/lmod.sh dest=/etc/profile.d/lmod.sh

  - name: slurm.sh al /etc/profile.d
    copy: src=/root/templates/slurm.sh dest=/etc/profile.d/slurm.sh

  - name: epel release instalada
    yum: name="epel-release" state=present

  - name: instalem nfs-utils
    yum: name="nfs-utils" state=present

  - name: creem /genomics/users
    file: path=/genomics/users state=directory

  - name: creem /projects_rg
    file: path=/projects_rg state=directory

  - name: creem /projects_eg
    file: path=/projects_eg state=directory

  - name: creem /projects_fg
    file: path=/projects_fg state=directory

  - name: muntem /genomics/users
    mount:
     path: /genomics/users
     src: beta:/genomics/users 
     fstype: nfs
     opts: ro,defaults,vers=3
     state: mounted

  - name: muntem /projects_rg
    mount:
      path: /projects_rg
      src: shannon:/projects_rg
      fstype: nfs
      opts: ro,defaults,vers=3
      state: mounted

  - name: muntem /projects_eg
    mount:
      path: /projects_eg
      src: wallace:/projects_eg
      fstype: nfs
      opts: ro,defaults,vers=3
      state: mounted

  - name: muntem /projects_fg
    mount:
      path: /projects_fg
      src: rabat:/projects_fg
      fstype: nfs
      opts: ro,defaults,vers=3
      state: mounted

     
